import type { AuditFields } from './resources';
import type { PaginationOptions } from '../common';
import type { Simplify } from '../util';

/**
 * Schema configuration
 */
export interface ResourceSchemaConfig<T> {
  // Resource identity
  ids: keyof T;

  // Fields that can never be changed after creation
  immutable?: keyof T;

  // Fields generated by the server
  serverGenerated?: keyof T;

  // Fields required to scope searches
  scope?: keyof T;

  // Fields optional to refine searches
  query?: Record<string, unknown>;
}

/**
 * Helper to parse or remove query
 */
type ResolveQuery<T, S extends ResourceSchemaConfig<T>> =
  S['query'] extends Record<string, unknown> ? Partial<S['query']> : unknown;

/**
 * Helper to strips audit fields
 */
type ClientWritable<T> = Omit<T, keyof AuditFields>;

/**
 * Resource-derived request generators
 */
export type CreateRequestDTO<T, S extends ResourceSchemaConfig<T>> = Simplify<
  Omit<ClientWritable<T>, S['serverGenerated'] extends keyof T ? S['serverGenerated'] : never>
>;

export type GetRequestDTO<T, S extends ResourceSchemaConfig<T>> = Simplify<Pick<T, S['ids']>>;

export type ListRequestDTO<T, S extends ResourceSchemaConfig<T>> = Simplify<
  Pick<T, S['scope'] extends keyof T ? S['scope'] : never> & ResolveQuery<T, S> & Partial<PaginationOptions>
>;

export type PutRequestDTO<T, S extends ResourceSchemaConfig<T>> = Simplify<
  Pick<T, S['ids']> & Omit<ClientWritable<T>, S['ids'] | (S['immutable'] extends keyof T ? S['immutable'] : never)>
>;

export type PatchRequestDTO<T, S extends ResourceSchemaConfig<T>> = Simplify<
  Pick<T, S['ids']> &
    Partial<Omit<ClientWritable<T>, S['ids'] | (S['immutable'] extends keyof T ? S['immutable'] : never)>>
>;

export type UpsertRequestDTO<T, S extends ResourceSchemaConfig<T>> = Simplify<
  Partial<Pick<T, S['ids']>> &
    Omit<ClientWritable<T>, S['ids'] | (S['immutable'] extends keyof T ? S['immutable'] : never)>
>;

export type DeleteRequestDTO<T, S extends ResourceSchemaConfig<T>> = Simplify<Pick<T, S['ids']>>;
