import type { GeoJSON } from 'geojson';
import type { IProject } from '@/interfaces/IProject';
import type { BasicResponse } from '@/utils/enums/application';
import type { NumResidentialUnits } from '@/utils/enums/housing';
import type { ProjectApplicant } from '@/utils/enums/projectCommon';

export type HousingProject = {
  housingProjectId: string;
  relatedEnquiries: string;
  projectApplicantType: ProjectApplicant;
  consentToFeedback?: boolean;
  geoJson?: GeoJSON;
  projectLocation: string;
  projectLocationDescription: string;
  singleFamilyUnits: NumResidentialUnits;
  multiFamilyUnits: NumResidentialUnits;
  otherUnitsDescription: string;
  otherUnits: NumResidentialUnits;
  hasRentalUnits: BasicResponse;
  rentalUnits: string;
  financiallySupportedBc: BasicResponse;
  financiallySupportedIndigenous: BasicResponse;
  indigenousDescription: string;
  financiallySupportedNonProfit: BasicResponse;
  nonProfitDescription: string;
  financiallySupportedHousingCoop: BasicResponse;
  housingCoopDescription: string;
  locality: string;
  province: string;
  locationPids: string;
  latitude: number;
  longitude: number;
  streetAddress: string;
  geomarkUrl: string;
  naturalDisaster: boolean;
  ltsaCompleted: boolean;
  bcOnlineCompleted: boolean;
  hasAppliedProvincialPermits: boolean;
} & IProject;
