import type { GeoJSON } from 'geojson';
import type { IProject } from '@/interfaces/IProject';
import type { BasicResponse } from '@/utils/enums/application';
import type { NumResidentialUnits } from '@/utils/enums/housing';
import type { ProjectApplicant } from '@/utils/enums/projectCommon';

export type HousingProject = {
  housingProjectId: string;
  relatedEnquiries: string;
  projectApplicantType: ProjectApplicant;
  consentToFeedback?: boolean;
  geoJson?: GeoJSON;
  projectLocation: string;
  projectLocationDescription?: string | null;
  singleFamilyUnits?: NumResidentialUnits | null;
  multiFamilyUnits?: NumResidentialUnits | null;
  otherUnitsDescription?: string | null;
  otherUnits?: NumResidentialUnits | null;
  hasRentalUnits: BasicResponse;
  rentalUnits: string;
  financiallySupportedBc: BasicResponse;
  financiallySupportedIndigenous: BasicResponse;
  indigenousDescription: string;
  financiallySupportedNonProfit: BasicResponse;
  nonProfitDescription: string;
  financiallySupportedHousingCoop: BasicResponse;
  housingCoopDescription: string;
  locality?: string | null;
  province?: string | null;
  locationPids?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  streetAddress?: string | null;
  geomarkUrl?: string | null;
  naturalDisaster: boolean;
  ltsaCompleted: boolean;
  bcOnlineCompleted: boolean;
  hasAppliedProvincialPermits: boolean;
} & IProject;
