import type { Activity } from './Activity';
import type { User } from './User';

export type Submission = {
  formId?: string;
  submissionId: string;
  submittedAt: string;
  submittedBy: string;
  locationPIDs?: string;
  contactName?: string;
  contactPhoneNumber?: string;
  contactEmail?: string;
  projectName?: string;
  companyNameRegistered?: string;
  singleFamilyUnits?: string;
  streetAddress?: string;
  latitude?: number;
  longitude?: number;
  queuePriority?: string;
  relatedPermits?: string;
  astNotes?: string;
  astUpdated: boolean;
  addedToATS: boolean;
  atsClientNumber: string;
  ltsaCompleted: boolean;
  naturalDisaster: boolean;
  financiallySupported: boolean;
  financiallySupportedBC: boolean;
  financiallySupportedIndigenous: boolean;
  financiallySupportedNonProfit: boolean;
  financiallySupportedHousingCoop: boolean;
  aaiUpdated: boolean;
  waitingOn?: string;
  bringForwardDate?: string;
  notes?: string;
  activity: Activity;
  user?: User; // assigned to
  intakeStatus?: string;
  applicationStatus?: string;
  guidance: boolean;
  statusRequest: boolean;
  inquiry: boolean;
  emergencyAssist: boolean;
  inapplicable: boolean;
};
