---
config:
  enabled: true
  configMap:
    FRONTEND_APIPATH: api/v1
    FRONTEND_CHES_BCC: NRM.PermittingAndData@gov.bc.ca
    FRONTEND_COMS_APIPATH: https://coms-test.api.gov.bc.ca/api/v1
    FRONTEND_COMS_BUCKETID: a9eabd1d-5f77-4c60-bf6b-83ffa0e21c59
    FRONTEND_GEOCODER_APIPATH: https://geocoder.api.gov.bc.ca
    FRONTEND_OIDC_AUTHORITY: https://test.loginproxy.gov.bc.ca/auth/realms/standard
    FRONTEND_OIDC_CLIENTID: nr-permit-connect-navigator-service-5188
    FRONTEND_ORGBOOK_APIPATH: https://orgbook.gov.bc.ca/api/v4
    SERVER_APIPATH: /api/v1
    SERVER_BODYLIMIT: 30mb
    SERVER_CHEFS_APIPATH: https://submit.digital.gov.bc.ca/app/api/v1
    SERVER_CHES_APIPATH: https://ches-test.api.gov.bc.ca/api/v1
    SERVER_CHES_TOKENURL: https://test.loginproxy.gov.bc.ca/auth/realms/comsvcauth/protocol/openid-connect/token
    SERVER_DB_PORT: "5432"
    # SERVER_LOGFILE: ~
    SERVER_LOGLEVEL: http
    SERVER_OIDC_AUTHORITY: https://test.loginproxy.gov.bc.ca/auth/realms/standard
    SERVER_OIDC_IDENTITYKEY: idir_user_guid,bceid_user_guid
    SERVER_OIDC_PUBLICKEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiFdv9GA83uHuy8Eu9yiZHGGF9j6J8t7FkbcpaN81GDjwbjsIJ0OJO9dKRAx6BAtTC4ubJTBJMPvQER5ikOhIeBi4o25fg61jpgsU6oRZHkCXc9gX6mrjMjbsPaf3/bjjYxP5jicBDJQeD1oRa24+tiGggoQ7k6gDEN+cRYqqNpzC/GQbkUPk8YsgroncEgu8ChMh/3ERsLV2zorchMANUq76max16mHrhtWIQxrb/STpSt4JuSlUzzBV/dcXjJe5gywZHe0jAutFhNqjHzHdgyaC4RAd3eYQo+Kl/JOgy2AZrnx+CiPmvOJKe9tAW4k4H087ng8aVE40v4HW/FEbnwIDAQAB
    SERVER_PORT: "8080"

patroni:
  enabled: true
