import { Activity } from './Activity';
import { User } from './User';
import { IStamps } from '../interfaces/IStamps';

export type Submission = {
  submissionId: string;
  submittedAt: string;
  submittedBy: string;
  locationPIDs: string | null;
  companyNameRegistered: string | null;
  contactName: string | null;
  contactPhoneNumber: string | null;
  contactEmail: string | null;
  projectName: string | null;
  singleFamilyUnits: string | null;
  streetAddress: string | null;
  latitude: number | null;
  longitude: number | null;
  queuePriority: number | null;
  relatedPermits: string | null;
  astNotes: string | null;
  astUpdated: boolean;
  addedToATS: boolean;
  atsClientNumber: string | null;
  ltsaCompleted: boolean;
  bcOnlineCompleted: boolean;
  naturalDisaster: boolean;
  financiallySupported: boolean;
  financiallySupportedBC: boolean;
  financiallySupportedIndigenous: boolean;
  financiallySupportedNonProfit: boolean;
  financiallySupportedHousingCoop: boolean;
  aaiUpdated: boolean;
  waitingOn: string | null;
  bringForwardDate: string | null;
  notes: string | null;
  activity: Activity | null;
  user: User | null; // assigned to
  intakeStatus: string | null;
  applicationStatus: string | null;
  guidance: boolean;
  statusRequest: boolean;
  inquiry: boolean;
  emergencyAssist: boolean;
  inapplicable: boolean;
} & Partial<IStamps>;
