{{- if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-openshift-ingress-to-{{ include "pcns.fullname" . }}-app
  labels:
    {{- include "pcns.labels" . | nindent 4 }}
spec:
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              network.openshift.io/policy-group: ingress
      ports:
        - port: {{ default "8080" .Values.config.configMap.SERVER_PORT | atoi }}
          protocol: TCP
  podSelector:
    matchLabels: {{- include "pcns.selectorLabels" . | nindent 6 }}
{{- if .Values.patroni.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-{{ include "pcns.fullname" . }}-app-to-patroni-cluster
  labels: {{ include "pcns.labels" . | nindent 4 }}
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels: {{ include "pcns.selectorLabels" . | nindent 14 }}
      ports:
        - port: {{ default "5432" .Values.config.configMap.SERVER_DB_PORT | atoi }}
          protocol: TCP
  podSelector:
    matchLabels:
      app: patroni
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-pre-hook-to-patroni-cluster
  labels: {{ include "pcns.labels" . | nindent 4 }}
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              openshift.io/deployer-pod.type: hook-pre
      ports:
        - port: {{ default "5432" .Values.config.configMap.SERVER_DB_PORT | atoi }}
          protocol: TCP
  podSelector:
    matchLabels:
      app: patroni
{{- if .Values.peachSync.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-{{ include "pcns.fullname" . }}-peach-sync-app-to-patroni-cluster
  labels: {{ include "pcns.labels" . | nindent 4 }}
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels: {{ include "pcns.peachSyncSelectorLabels" . | nindent 14 }}
      ports:
        - port: {{ default "5432" .Values.config.configMap.SERVER_DB_PORT | atoi }}
          protocol: TCP
  podSelector:
    matchLabels:
      app: patroni
{{- end }}
{{- end }}
{{- end }}
