{{- $dbHostName := .Values.database.host | default .Values.config.configMap.SERVER_DB_HOST -}}
{{- $dbSecretName := .Values.database.secretName | default (printf "%s-%s" (include "pcns.fullname" .) "passphrase") -}}

{{- $dbDbKey := default "dbname" (and .Values.database .Values.database.secretKeys .Values.database.secretKeys.database) -}}
{{- $dbUserKey := default "user" (and .Values.database .Values.database.secretKeys .Values.database.secretKeys.username) -}}
{{- $dbPassKey := default "password" (and .Values.database .Values.database.secretKeys .Values.database.secretKeys.password) -}}

{{- if .Values.patroni }}
{{- if .Values.patroni.enabled }}
{{- if .Subcharts.patroni }}
{{- $dbHostName = include "patroni.fullname" .Subcharts.patroni -}}
{{- $dbSecretName = include "patroni.fullname" .Subcharts.patroni -}}
{{- $dbDbKey = "app-db-name" -}}
{{- $dbUserKey = "app-db-username" -}}
{{- $dbPassKey = "app-db-password" -}}
{{- end -}}
{{- end -}}
{{- end -}}

apiVersion: batch/v1
kind: CronJob
metadata:
  name: peach-sync
  labels:
    {{- include "pcns.peachSyncLabels" . | nindent 4 }}
spec:
  schedule: {{ .Values.peachSync.schedule | quote }}
  suspend: {{ .Values.peachSync.suspend }}
  startingDeadlineSeconds: {{ .Values.peachSync.startingDeadlineSeconds  }}
  concurrencyPolicy: {{ .Values.peachSync.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.peachSync.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.peachSync.failedJobsHistoryLimit }}
  jobTemplate:
    metadata:
      labels:
        {{- include "pcns.peachSyncSelectorLabels" . | nindent 8 }}
    spec:
      backoffLimit: {{ .Values.peachSync.backoffLimit }}
      activeDeadlineSeconds: {{ .Values.peachSync.activeDeadlineSeconds }}
      template:
        metadata:
          labels:
            {{- include "pcns.peachSyncLabels" . | nindent 12 }}
        spec:
          restartPolicy: Never
          terminationGracePeriodSeconds: {{ .Values.peachSync.terminationGracePeriodSeconds }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: peach-sync
              image: "{{ .Values.image.repository }}/{{ .Chart.Name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - /usr/local/bin/node
                - sbin/peachSync.js
              resources:
                {{- toYaml .Values.peachSync.resources | nindent 16 }}
              env:
                - name: NODE_ENV
                  value: production
                - name: SERVER_LOGLEVEL
                  value: "verbose"
                - name: SERVER_DB_DATABASE
                  valueFrom:
                    secretKeyRef:
                      key: {{ $dbDbKey }}
                      name: {{ $dbSecretName }}
                - name: SERVER_DB_HOST
                  value: {{ $dbHostName | quote }}
                - name: SERVER_DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      key: {{ $dbUserKey }}
                      name: {{ $dbSecretName }}
                - name: SERVER_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: {{ $dbPassKey }}
                      name: {{ $dbSecretName }}
                - name: SERVER_CHES_CLIENTID
                  valueFrom:
                    secretKeyRef:
                      key: username
                      name: {{ include "pcns.configname" . }}-ches-service-account
                - name: SERVER_CHES_CLIENTSECRET
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: {{ include "pcns.configname" . }}-ches-service-account
                - name: SERVER_PEACH_CLIENTID
                  valueFrom:
                    secretKeyRef:
                      key: username
                      name: {{ include "pcns.configname" . }}-peach
                - name: SERVER_PEACH_CLIENTSECRET
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: {{ include "pcns.configname" . }}-peach
              envFrom:
                - configMapRef:
                    name: {{ include "pcns.configname" . }}-config
