// AUTO-GENERATED FILE - DO NOT EDIT
/* eslint-disable max-len */

export const ElectrificationProjectCategory = {
  CONNECTIVITY: 'CONNECTIVITY',
  INTERCONNECTIVITY: 'INTERCONNECTIVITY',
  IPP: 'IPP',
  REMOTE_RENEWABLE: 'REMOTE_RENEWABLE',
  SUSTAINMENT: 'SUSTAINMENT'
} as const;

export type ElectrificationProjectCategory =
  (typeof ElectrificationProjectCategory)[keyof typeof ElectrificationProjectCategory];

export const ElectrificationProjectType = {
  IPP_HYDRO: 'IPP_HYDRO',
  IPP_SOLAR: 'IPP_SOLAR',
  IPP_WIND: 'IPP_WIND',
  OTHER: 'OTHER'
} as const;

export type ElectrificationProjectType = (typeof ElectrificationProjectType)[keyof typeof ElectrificationProjectType];

export const SourceSystem = {
  ITSM_5285: 'ITSM-5285',
  ITSM_5314: 'ITSM-5314',
  ITSM_5364: 'ITSM-5364',
  ITSM_5527: 'ITSM-5527',
  ITSM_5528: 'ITSM-5528',
  ITSM_5644: 'ITSM-5644',
  ITSM_5816: 'ITSM-5816',
  ITSM_5939: 'ITSM-5939',
  ITSM_5963: 'ITSM-5963',
  ITSM_6004: 'ITSM-6004',
  ITSM_60081: 'ITSM-60081',
  ITSM_6030: 'ITSM-6030',
  ITSM_6072: 'ITSM-6072',
  ITSM_6117: 'ITSM-6117',
  ITSM_6136: 'ITSM-6136',
  ITSM_6197: 'ITSM-6197'
} as const;

export type SourceSystem = (typeof SourceSystem)[keyof typeof SourceSystem];

export const EscalationType = {
  MINISTRY: 'MINISTRY',
  OTHER: 'OTHER',
  PROPONENT: 'PROPONENT',
  TIME_SENSITIVE: 'TIME_SENSITIVE'
} as const;

export type EscalationType = (typeof EscalationType)[keyof typeof EscalationType];

export const BusinessArea = {
  ABORIGINAL_RELATIONS: 'ABORIGINAL_RELATIONS',
  ADVANCED_EDUCATION: 'ADVANCED_EDUCATION',
  AGRICULTURAL_LAND_COMMISSION: 'AGRICULTURAL_LAND_COMMISSION',
  AGRICULTURE: 'AGRICULTURE',
  ARCHAEOLOGY: 'ARCHAEOLOGY',
  BC_ASSESSMENT_AUTHORITY: 'BC_ASSESSMENT_AUTHORITY',
  BC_ENERGY_REGULATOR: 'BC_ENERGY_REGULATOR',
  COMMUNITY_DEVELOPMENT: 'COMMUNITY_DEVELOPMENT',
  COMMUNITY_SPORT_AND_CULTURE: 'COMMUNITY_SPORT_AND_CULTURE',
  DEPARTMENT_OF_FISHERIES_AND_OCEANS_CANADA: 'DEPARTMENT_OF_FISHERIES_AND_OCEANS_CANADA',
  ECONOMIC_DEVELOPMENT: 'ECONOMIC_DEVELOPMENT',
  EDUCATION: 'EDUCATION',
  ELECTRIFICATION: 'ELECTRIFICATION',
  ENERGY: 'ENERGY',
  ENVIRONMENT: 'ENVIRONMENT',
  ENVIRONMENTAL_PROTECTION: 'ENVIRONMENTAL_PROTECTION',
  FEDERAL_GOVERNMENT: 'FEDERAL_GOVERNMENT',
  FINANCE: 'FINANCE',
  FISH_AND_WILDLIFE: 'FISH_AND_WILDLIFE',
  FORESTS: 'FORESTS',
  FRASER_HEALTH_AUTHORITY: 'FRASER_HEALTH_AUTHORITY',
  HEALTH_SERVICES: 'HEALTH_SERVICES',
  INTERIOR_HEALTH_AUTHORITY: 'INTERIOR_HEALTH_AUTHORITY',
  LABOUR_AND_CITIZENS_SERVICES: 'LABOUR_AND_CITIZENS_SERVICES',
  LANDS: 'LANDS',
  LAND_TITLE_AUTHORITY: 'LAND_TITLE_AUTHORITY',
  LOCAL_GOVERNMENT_MUNICIPALITIES_AND_CITIES: 'LOCAL_GOVERNMENT_MUNICIPALITIES_AND_CITIES',
  MINES: 'MINES',
  MINISTRY_OF_ATTORNEY_GENERAL: 'MINISTRY_OF_ATTORNEY_GENERAL',
  MINISTRY_OF_SMALL_BUSINESS_AND_REVENUE: 'MINISTRY_OF_SMALL_BUSINESS_AND_REVENUE',
  MOUNTAIN_RESORTS_BRANCH: 'MOUNTAIN_RESORTS_BRANCH',
  NON_LISTED_PARTNER_AGENCY_OR_OTHER: 'NON_LISTED_PARTNER_AGENCY_OR_OTHER',
  NORTHERN_HEALTH_AUTHORITY: 'NORTHERN_HEALTH_AUTHORITY',
  OFFICE_OF_THE_PREMIER: 'OFFICE_OF_THE_PREMIER',
  PARKS: 'PARKS',
  PROVINCIAL_EMERGENCY_PROGRAM: 'PROVINCIAL_EMERGENCY_PROGRAM',
  PUBLIC_SERVICE_AGENCY: 'PUBLIC_SERVICE_AGENCY',
  RANGE: 'RANGE',
  RECREATION_SITES_AND_TRAILS: 'RECREATION_SITES_AND_TRAILS',
  REGIONAL_DISTRICTS: 'REGIONAL_DISTRICTS',
  RIPARIAN: 'RIPARIAN',
  RURAL_DEVELOPMENT: 'RURAL_DEVELOPMENT',
  SMALL_BUSINESS_BC: 'SMALL_BUSINESS_BC',
  SOLICITOR_GENERAL: 'SOLICITOR_GENERAL',
  SURVEYOR_GENERAL_LAND_TITLE_AND_SURVEY_AUTHORITIES: 'SURVEYOR_GENERAL_LAND_TITLE_AND_SURVEY_AUTHORITIES',
  SYSTEMS: 'SYSTEMS',
  TRANSPORTATION: 'TRANSPORTATION',
  VANCOUVER_COAST_HEALTH_AUTHORITY: 'VANCOUVER_COAST_HEALTH_AUTHORITY',
  VANCOUVER_ISLAND_HEALTH_AUTHORITY: 'VANCOUVER_ISLAND_HEALTH_AUTHORITY',
  WATER: 'WATER'
} as const;

export type BusinessArea = (typeof BusinessArea)[keyof typeof BusinessArea];

export const PermitStage = {
  APPLICATION_SUBMISSION: 'APPLICATION_SUBMISSION',
  PENDING_DECISION: 'PENDING_DECISION',
  POST_DECISION: 'POST_DECISION',
  PRE_SUBMISSION: 'PRE_SUBMISSION',
  TECHNICAL_REVIEW: 'TECHNICAL_REVIEW'
} as const;

export type PermitStage = (typeof PermitStage)[keyof typeof PermitStage];

export const PermitState = {
  ACCEPTED: 'ACCEPTED',
  APPROVED: 'APPROVED',
  CANCELLED: 'CANCELLED',
  DENIED: 'DENIED',
  INITIAL_REVIEW: 'INITIAL_REVIEW',
  IN_PROGRESS: 'IN_PROGRESS',
  ISSUED: 'ISSUED',
  NONE: 'NONE',
  PENDING_APPLICANT_ACTION: 'PENDING_APPLICANT_ACTION',
  REJECTED: 'REJECTED',
  WITHDRAWN: 'WITHDRAWN'
} as const;

export type PermitState = (typeof PermitState)[keyof typeof PermitState];
