/* eslint-disable max-len */
import stamps from '../stamps';

import type { Knex } from 'knex';

export async function up(knex: Knex): Promise<void> {
  return Promise.resolve().then(() =>
    // Create public schema tables
    knex.schema
      .createTable('source_system_code', (table) => {
        table.text('code').primary(); //.checkRegex('^ITSM-\\d{4,5}$'); // TODO: NO_SYSTEM messes this regex up
        table.text('display').unique().notNullable();
        table.text('definition').notNullable();
        table.boolean('active').notNullable().defaultTo(true);
        table.text('acronym').notNullable();
        table.text('source_key_name').notNullable();
        stamps(knex, table);
      })

      .createTable('permit_tracking', (table) => {
        table.specificType('permit_tracking_id', 'integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
        table
          .uuid('permit_id')
          .notNullable()
          .references('permit_id')
          .inTable('permit')
          .onUpdate('CASCADE')
          .onDelete('CASCADE');
        table.text('tracking_id');
        table
          .text('source_system_code')
          .notNullable()
          .references('code')
          .inTable('source_system_code')
          .onUpdate('CASCADE')
          .onDelete('CASCADE');
        table.boolean('shown_to_proponent').notNullable().defaultTo(false);
        stamps(knex, table);
      })

      // Alter public schema tables
      .alterTable('permit_type', (table) => {
        table
          .text('source_system_code')
          //.notNullable() // TODO: Not nullable or default to NO_SYSTEM?
          .references('code')
          .inTable('source_system_code')
          .onUpdate('CASCADE')
          .onDelete('CASCADE'); // TODO: Do we want to delete types if their source is deleted?
      })

      // Create before update triggers
      .then(() =>
        knex.schema.raw(`CREATE TRIGGER before_update_source_system_code_trigger
          BEFORE UPDATE ON source_system_code
          FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();`)
      )

      .then(() =>
        knex.schema.raw(`CREATE TRIGGER before_update_permit_tracking_trigger
          BEFORE UPDATE ON permit_tracking
          FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();`)
      )

      // Create audit triggers
      .then(() =>
        knex.schema.raw(`CREATE TRIGGER audit_source_system_code_trigger
          AFTER UPDATE OR DELETE ON source_system_code
          FOR EACH ROW EXECUTE PROCEDURE audit.if_modified_func();`)
      )

      .then(() =>
        knex.schema.raw(`CREATE TRIGGER audit_permit_tracking_trigger
          AFTER UPDATE OR DELETE ON permit_tracking
          FOR EACH ROW EXECUTE PROCEDURE audit.if_modified_func();`)
      )

      // Populate source sysem codes
      .then(() => {
        return knex('source_system_code').insert([
          {
            code: 'ITSM-5285',
            display: 'Archaeology Permit Tracking System',
            definition: 'Archaeology Permit Tracking System',
            acronym: 'APTS',
            source_key_name: 'TBD'
          },
          {
            code: 'ITSM-5364',
            display: 'Contaminated Sites Application Tracking System',
            definition: 'Contaminated Sites Application Tracking System',
            acronym: 'CATS',
            source_key_name: 'TBD'
          },
          // {
          //   code: '', // TODO: Not in Jira Assets? Transportation permits will have no associated system
          //   display: 'Electronic Development Approvals System',
          //   definition: 'Electronic Development Approvals System',
          //   acronym: 'eDAS',
          //   source_key_name: 'TBD'
          // },
          {
            code: 'ITSM-5527',
            display: 'POSSE (ELicencing)', // TODO: Is this right? Different in Jira Assets. POSSE is the alias
            definition: 'POSSE (ELicencing)',
            acronym: 'ELIC',
            source_key_name: 'TBD'
          },
          {
            code: 'ITSM-5939',
            display: 'Electronic Park Use Permit System',
            definition: 'Electronic Park Use Permit System',
            acronym: 'EPUPS', // TODO: Actually called PPA in Jira Assets
            source_key_name: 'TBD'
          },
          {
            code: 'ITSM-5644',
            display: 'Forest Tenure Administration',
            definition: 'Forest Tenure Administration',
            acronym: 'FTA',
            source_key_name: 'TBD'
          },
          {
            code: 'ITSM-5816',
            display: 'Mines Digital Services',
            definition: 'Mines Digital Services',
            acronym: 'MDS',
            source_key_name: 'TBD'
          },
          {
            code: 'NO_SYSTEM', // TODO: Terrible idea? All permits should have a system but need a default for migration
            display: 'NO SYSTEM',
            definition: 'Custom code for an unknown or non existent system',
            acronym: 'NA',
            source_key_name: 'TBD'
          },
          {
            code: 'ITSM-5963',
            display: 'Riparian Areas Regulation Notification System',
            definition: 'Riparian Areas Regulation Notification System',
            acronym: 'RARN', // TODO: Actually called RAR in Jira Assets
            source_key_name: 'TBD'
          },
          {
            code: 'ITSM-6004',
            display: 'Resource Roads System',
            definition: 'Resource Roads System',
            acronym: 'RRS',
            source_key_name: 'TBD'
          },
          {
            code: 'ITSM-6072',
            display: 'Tantalis',
            definition: 'Tantalis',
            acronym: 'TANTALIS',
            source_key_name: 'TBD'
          },
          {
            code: 'ITSM-6136',
            display: 'Waste Permit Administration System',
            definition: 'Waste Permit Administration System',
            acronym: 'WASTE',
            source_key_name: 'TBD'
          },
          {
            code: 'ITSM-6197',
            display: 'Water Management Application',
            definition: 'Water Management Application',
            acronym: 'WMA',
            source_key_name: 'TBD'
          }
        ]);
      })

      // Split permit tracking ids
      // Default to NO_SYSTEM as we dont have this information
      .then(async () => {
        await knex.raw(`INSERT INTO public.permit_tracking (permit_id, tracking_id, source_system_code)
            SELECT permit_id, tracking_id, 'NO_SYSTEM'
            FROM public.permit;`);
      })

      // Update permit_type to FK to new source_system_code
      .then(async () => {
        await knex.raw(`UPDATE public.permit_type SET (source_system_code) =
          (SELECT code
          FROM public.source_system_code
          WHERE source_system_code.acronym = public.permit_type.source_system_acronym);`);
      })

      // Drop old columns
      .then(() =>
        knex.schema.alterTable('permit', function (table) {
          table.dropColumn('tracking_id');
        })
      )

      .then(() =>
        knex.schema.alterTable('permit_type', function (table) {
          table.dropColumn('source_system');
          table.dropColumn('source_system_acronym');
        })
      )
  );
}

export async function down(knex: Knex): Promise<void> {
  return (
    Promise.resolve()
      // Add columns
      .then(() =>
        knex.schema.alterTable('permit_type', function (table) {
          table.text('source_system');
          table.text('source_system_acronym');
        })
      )

      .then(() =>
        knex.schema.alterTable('permit', function (table) {
          table.text('tracking_id');
        })
      )

      // Update permit_type to old source name/acronym
      .then(async () => {
        await knex.raw(`UPDATE public.permit_type SET (source_system, source_system_acronym) =
          (SELECT display, acronym
          FROM public.source_system_code
          WHERE source_system_code.code = public.permit_type.source_system_code);`);
      })

      // Add permit tracking ids back
      .then(() =>
        knex.schema.raw(`
          UPDATE public.permit AS p
            set tracking_id = pt.tracking_id
          FROM public.permit_tracking pt
          WHERE p.permit_id = pt.permit_id;`)
      )

      // Drop audit triggers
      .then(() => knex.schema.raw('DROP TRIGGER IF EXISTS audit_permit_tracking_trigger ON permit_tracking'))
      .then(() => knex.schema.raw('DROP TRIGGER IF EXISTS audit_source_system_code_trigger ON source_system_code'))

      // Drop public schema table triggers
      .then(() => knex.schema.raw('DROP TRIGGER IF EXISTS before_update_permit_tracking_trigger ON permit_tracking'))
      .then(() =>
        knex.schema.raw('DROP TRIGGER IF EXISTS before_update_source_system_code_trigger ON source_system_code')
      )

      // Alter public schema tables
      .then(() =>
        knex.schema.alterTable('permit_type', function (table) {
          table.dropColumn('source_system_code');
        })
      )

      // Drop public schema tables
      .then(() => knex.schema.dropTableIfExists('permit_tracking'))
      .then(() => knex.schema.dropTableIfExists('source_system_code'))
  );
}
