name: Push

on:
  push:
    branches:
      - master
    tags:
      - v*.*.*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Push
    uses: ./.github/workflows/builder.yaml
    permissions:
      contents: read
      packages: write
    with:
      context: .
      image_name: ${{ vars.APP_NAME }}
      github_username: ${{ github.repository_owner }}
    secrets:
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}

  deploy-dev:
    name: Deploy to Dev
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    uses: ./.github/workflows/deployer.yaml
    permissions:
      contents: read
    with:
      app_name: ${{ vars.APP_NAME }}
      acronym: ${{ vars.ACRONYM }}
      environment: dev
      image_tag: ${{ needs.build.outputs.image_tag }}
      job_name: master
      namespace_prefix: ${{ vars.NAMESPACE_PREFIX }}
      namespace_environment: dev
    secrets:
      openshift_server: ${{ secrets.OPENSHIFT_SERVER }}
      openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}

  deploy-test:
    name: Deploy to Test
    needs:
      - build
      - deploy-dev
    uses: ./.github/workflows/deployer.yaml
    permissions:
      contents: read
    with:
      app_name: ${{ vars.APP_NAME }}
      acronym: ${{ vars.ACRONYM }}
      environment: test
      image_tag: ${{ needs.build.outputs.image_tag }}
      job_name: master
      namespace_prefix: ${{ vars.NAMESPACE_PREFIX }}
      namespace_environment: test
    secrets:
      openshift_server: ${{ secrets.OPENSHIFT_SERVER }}
      openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}

  deploy-prod:
    name: Deploy to Prod
    needs:
      - build
      - deploy-dev
      - deploy-test
    uses: ./.github/workflows/deployer.yaml
    permissions:
      contents: read
    with:
      app_name: ${{ vars.APP_NAME }}
      acronym: ${{ vars.ACRONYM }}
      environment: prod
      image_tag: ${{ needs.build.outputs.image_tag }}
      job_name: master
      namespace_prefix: ${{ vars.NAMESPACE_PREFIX }}
      namespace_environment: prod
    secrets:
      openshift_server: ${{ secrets.OPENSHIFT_SERVER }}
      openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
